### ISSUE TITLE
SSL Certification Error 581

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#104] opened 2016-04-27 23:11 UTC
So I try to update the program and in I get:

`Youtube-dl download failed [<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate failed (_ssl.c:581)>]`

Appears the same with or without any link on the download field
This is the log:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyc", line 810, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 248, in run
  File "youtube_dl_gui\downloaders.pyc", line 105, in download
  File "youtube_dl_gui\downloaders.pyc", line 292, in _create_process
  File "subprocess.pyc", line 710, in __init__
  File "subprocess.pyc", line 958, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified

```

I already tried ussing the _--no-check-certificate_ option and clearing the SSL certificates on Internet Options

**Comment by NightSparkle** [comment] 2016-04-27 23:52
Also, I tested the [command line](https://rg3.github.io/youtube-dl/download.html)  youtube-dl and it's working.

**Comment by MrS0m30n3** [comment] 2016-09-14 10:46
Hi, 

This messages means that something went wrong with establishing the SSL connection, its not a bug in the software. Also the log seems to be from a totally different issue. Downloadmanager has nothing to do with the update process. The message says that the system could not find the file (youtube-dl.exe) because the update failed and there is no such file.

I am closing this.

**Closed by MrS0m30n3** 2016-09-14 10:46 UTC
