### ISSUE TITLE
youtube-dl-gui (youtube-dlg) only downloads m4a even though mp4 is selected

### ISSUE THREAD

**Issue by IoanPaleru** [MrS0m30n3/youtube-dl-gui#307] opened 2018-05-05 21:47 UTC
- [x] **I think** my problem is **NOT** with **youtube-dl**
- [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
- [x] **I assure** that i am using the latest version of **youtube-dl**
- [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
- [x] I've read the FAQs file

- [x] Question

The log is blank, because it says "downloads completed", even though it downloads an .m4a file instead of an .mp4 file.

Windows 7 home premium 64-bit

1. Open youtube-dl-gui (youtube-dlg)
2. Download any vevo video from youtube using the "mp4" setting from the drop-down menu.

It should download an .mp4 with video and audio streams.

It downloads an .m4a file even though "mp4" is selected. Is there a way to fix that? Thanks.

**Comment by nodiscc** [comment] 2018-07-08 18:39
I cannot reproduce (on Linux):

 * Select `mp4` in dropdown menu
 * https://www.youtube.com/watch?v=9Z4Mx9nlcPo
 * Click `Add`
 * Click the download button
 * Wait for the download to finish
 * file `M.I.A. - Exodus (Audio).mp4` exists and is an mp4 video file

@IoanPaleru do you still have this problem? After reinstalling?

**Comment by IoanPaleru** [comment] 2018-07-10 20:56
After reinstalling youtube-dl-gui (Youtube-DLG) 0.4 Portable, it seems to work properly now. However, is there a way to download the 480p mp4 and m4a DASH formats for this video "https://www.youtube.com/watch?v=Zi_XLOBDo_Y" and get youtube-dl-gui (Youtube-DLG) 0.4 Portable to automatically convert and combine them? Thanks. Have a good day.

**Comment by nodiscc** [comment] 2018-07-11 19:46
> get it to download the 480p mp4 and m4a DASH formats for this videoand automatically convert and combine them into an mp4 file

I don't think it is possible. You can only download those specific formats for this video:

```
$ youtube-dl --list-formats https://www.youtube.com/watch?v=LOBDo_Y
[youtube] Zi_XLOBDo_Y: Downloading webpage
[youtube] Zi_XLOBDo_Y: Downloading video info webpage
[youtube] Zi_XLOBDo_Y: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] Zi_XLOBDo_Y: Downloading js player vflAHKVO-
[info] Available formats for Zi_XLOBDo_Y:
format code  extension  resolution note
249          webm       audio only DASH audio   54k , opus @ 50k, 1.77MiB
250          webm       audio only DASH audio   71k , opus @ 70k, 2.34MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 4.48MiB
251          webm       audio only DASH audio  144k , opus @160k, 4.71MiB
171          webm       audio only DASH audio  148k , vorbis@128k, 4.69MiB
278          webm       192x144    144p   78k , webm container, vp9, 30fps, video only, 2.35MiB
160          mp4        192x144    144p   85k , avc1.4d400c, 30fps, video only, 1.80MiB
133          mp4        320x240    240p  159k , avc1.4d400d, 30fps, video only, 3.21MiB
242          webm       320x240    240p  170k , vp9, 30fps, video only, 4.87MiB
243          webm       480x360    360p  306k , vp9, 30fps, video only, 8.72MiB
134          mp4        480x360    360p  389k , avc1.4d401e, 30fps, video only, 8.33MiB
244          webm       640x480    480p  567k , vp9, 30fps, video only, 15.86MiB
135          mp4        640x480    480p  805k , avc1.4d401e, 30fps, video only, 17.30MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x240    small , mp4v.20.3, mp4a.40.2
18           mp4        480x360    medium , avc1.42001E, mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0, vorbis@128k (best)
````

You would have to use `--formats 140,134` and somehow recombine the 2 downloaded files in ffmpeg (manually or script). Anyway this is out of scope for youtube-dlg and you will be better served by using `youtube-dl` advanced [command line options](https://github.com/rg3/youtube-dl#format-selection).

**Closed by nodiscc** 2018-07-11 19:46 UTC
Labels: need info, windows
