### ISSUE TITLE
youtube-dl is blocked!

### ISSUE THREAD

**Issue by Droid-MAX** [MrS0m30n3/youtube-dl-gui#480] opened 2020-10-24 01:52 UTC
All repo related to youtube-dl have been blocked due to dcma

**Comment by FMecha** [comment] 2020-10-24 05:30
[Further details](https://github.com/github/dmca/pull/8122)

**Comment by axcore** [comment] 2020-10-24 10:20
>All repo related to youtube-dl have been blocked due to dcma

youtube-dl can still be downloaded via pip.

**Comment by FMecha** [comment] 2020-10-24 17:38
> > All repo related to youtube-dl have been blocked due to dcma
> 
> youtube-dl can still be downloaded via pip.

Issue here for dlg is that may break the updater feature, although I don't know if dlg's updater uses pip or not.

**Comment by OOPMan** [comment] 2020-10-25 01:45
It's unlikely that it uses pip.

If https://github.com/l1ving/youtube-dl (A copyright-respecting fork of the original repo) takes off as the new point of development then it can be used as a replacement

**Comment by FMecha** [comment] 2020-10-25 11:51
Just a quick test - dlg's updater still works... for now.

**Comment by putradimas** [comment] 2020-10-26 08:13
youtube-dl-gui uses yt-dl.org, and downloads still work on their site.

https://github.com/MrS0m30n3/youtube-dl-gui/blob/57eb51ccc8e2df4e8c766b31d677513adb5c86cb/youtube_dl_gui/updatemanager.py#L48

**Comment by FanboyStudios** [comment] 2020-10-28 21:58
I have a feature suggestion. 

What if we could have in the configuration options a place where we could place a link to the youtube-dl downloads? If youtube-dl gets taken offline because of evil companies/government entities... then we could just paste in a link to any functional fork that may still exist and still update the youtube-dl binaries.

This way we're not relying on the availability of a single fork, but rather have the option to get the binaries from pretty much anywhere making it more difficult for this software to be killed off.


Additionally, it could of course still be shipped pre-configured with a default like it is now.

**Comment by makew0rld** [comment] 2020-10-29 02:41
@MrS0m30n3 I would suggest switching to [yt-dlc](https://github.com/blackjack4494/yt-dlc). youtube-dl**c** has existed as a fork of youtube-dl for a long time now, merging many PRs since development on the main repo has slowed down. The link I've posted is just a recent reupload of the repo. It also has removed copyright infringing content. Currently seems like the best way forward. Even if development stopped today (it won't) it would still be an improvement, because it's merged many more PRs than the original repo.

**Comment by axcore** [comment] 2020-10-29 07:35
This project is not being maintained any more. [This fork](https://github.com/axcore/tartube) supports both youtube-dl and youtube-dlc.

**Comment by IdreesM0** [comment] 2020-10-29 14:30
Im getting ERROR: Unable to extract JS PLAYER URL eventhough I just installed the latest version of youtube-dlc. I can't see what the problem is anymore.

**Comment by makew0rld** [comment] 2020-10-29 15:31
@IdreesM0 that's a bug with the latest youtube-dlc version. It will be fixed.

**Comment by Gerbil-IT** [comment] 2020-10-31 19:54
@makeworld-the-better-one  hello, any timeline on this JS PLAYER URL issue ?

**Comment by makew0rld** [comment] 2020-10-31 20:22
@Gerbil-IT I'm not affiliated with any of these projects, but that issue has been fixed in the latest version of youtube-dlc.

https://github.com/blackjack4494/yt-dlc

**Closed as completed** 2021-04-01 09:35 UTC
