### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by alchemisty** [MrS0m30n3/youtube-dl-gui#72] opened 2016-01-26 10:07 UTC
youtube-dl-gui-0.3.7-win-portable.zip

Traceback (most recent call last):
  File "__main__.py", line 35, in <module>
  File "youtube_dl_gui\__init__.pyc", line 52, in <module>
  File "youtube_dl_gui\utils.pyc", line 93, in get_config_path
  File "ntpath.pyc", line 84, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 7: ordinal not in range(128)

youtube-dl-gui-0.3.8-win-portable.zip

Traceback (most recent call last):
  File "youtube-dl-gui", line 35, in <module>
  File "youtube_dl_gui\__init__.pyc", line 52, in <module>
  File "youtube_dl_gui\utils.pyc", line 94, in get_config_path
  File "ntpath.pyc", line 84, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 7: ordinal not in range(128)

youtube-dl-gui-0.3.8-win-portable-6377928.zip

Traceback (most recent call last):
  File "youtube-dl-gui", line 35, in <module>
  File "youtube_dl_gui\__init__.pyc", line 54, in <module>
  File "youtube_dl_gui\optionsmanager.pyc", line 51, in __init__
  File "youtube_dl_gui\optionsmanager.pyc", line 201, in load_default
  File "ntpath.pyc", line 310, in expanduser
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 9: ordinal not in range(128)

**Comment by MrS0m30n3** [comment] 2016-02-05 17:14
Hi @alchemisty 

This is a known bug (i believe you already know it since you found the patched version).
You should post in the https://github.com/MrS0m30n3/youtube-dl-gui/issues/57 if you have more questions regarding this bug.

Anyway, i am closing this since it's a duplicate of issue https://github.com/MrS0m30n3/youtube-dl-gui/issues/57

**Closed by MrS0m30n3** 2016-02-05 17:14 UTC
