### ISSUE TITLE
Auto close program when done

### ISSUE THREAD

**Issue by phd21** [MrS0m30n3/youtube-dl-gui#150] opened 2017-01-17 02:28 UTC
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

#### What operating system do you use ?
Linux Mint 17.x and Linux Mint 18.x  (KDE)

Αdd ability to schedule a starting date and time for downloads and an auto close option when done.

**Comment by nodiscc** [comment] 2017-01-17 08:43
Scheduling: duplicate of https://github.com/MrS0m30n3/youtube-dl-gui/issues/89

**Comment by MrS0m30n3** [comment] 2017-01-18 13:33
There was also a discussion on closing the program on download completion in issue [#131](https://github.com/MrS0m30n3/youtube-dl-gui/issues/131#issuecomment-249063919).

**Closed** 2017-01-18 14:55 UTC
Labels: duplicate

**Comment by phd21** [comment] 2017-01-18 15:45
Hi Everyone,
To:"nodiscc" If the application had a scheduling function and an option to close itself (the app) then it would be prudent to create a "log" text file with the date and time and other relveant information.

The reason I even add this request, if it is not already obvious, is to make it easier for users using the desktop "GUI" version versus the console terminal command line. If you have a bunch of downloads to do, then being able to schedule that at times when you are not using the computer (late at night or early morning) is convenient. And more importantly, users with limited subscription based Internet access (ISP) can schedule downloads during off peak hours to save money, and airtime.

**Comment by nodiscc** [comment] 2017-01-18 17:57
> being able to schedule that at times when you are not using the computer is convenient

I fully agree with this but very extensive scheduling capabilities are made available by the OS (Scheduled Tasks on Win, cron/gnome-schedule/... on Linux) and I think users should rely on that tried-and-true solution, instead of adding scheduling to youtube-dl which would not only lead to duplicate functionality, but also be less convenient and tweakable than the OS's scheduler.

**Comment by MrS0m30n3** [comment] 2017-01-18 20:37
Again, i have already expressed my opinion about the auto close feature in #131
Regarding the scheduling you can read #63

All i can say, is that the *users will be able to schedule their downloads using the OS scheduler* and not directly from **youtube-dlg**, but it's to early to talk about actual implementations.

**Comment by phd21** [comment] 2017-01-18 23:56
Hi Everyone,  MrS0m30n3, nodiscc,

"MrS0m30n3" are you the developer, and nodiscc is a "collaborator" developer? If so, thank you for providing this excellent application.

As for the "auto-shutdown" feature, I mean closing the "YouTube-DLG" application versus shutting down the whole computer system. I never tried the existing "Shutdown" option, because I am assuming it will shutdown my computer which I do not want. Adding to the existing log feature for more verbose logs, what was downloaded, errors if any per download, etc...

There are many ways in all operating systems to schedule applications to run from the console terminal command prompt in Linux ("at") , or the command prompt in MS Windows, or from numerous desktop applications as well. Most alarm, or reminder, or task scheduling applications do have options to run desktop applications (youtube-dlg) and or commands (youtube-dl).  In Linux, my KDE has excellent "Kalarm", and there are applets, desklets, widgets, and these: "Indicator Remindor", "alarm-clock", "Remind", etc...  I tried "Kalarm" and "Indicator Remindor" and it worked fine with "youtube-dl", but for a list of downloads, you have to manually create a text file with all the download URLs.

And, since you already have this really nice graphical front-end "youtube-dlg" for "youtube-dl", if and when you get a chance, enhancing it would make this even better for us users.  

Even without adding its own scheduling options, you might consider some other features. Like as "nodiscc" mentioned, perhaps an option to "resume". Of course to resume you have to have a list of downloads stored somewhere. Maybe adding a button to "save the current downloads" into a "YouTube-DLG_Date_Time.txt" text file, or just "YouTube-DLG.txt" that is automatically looked for and read when this "TouTube-DLG" application starts?

Thank you again for your consideration...
Phil
phd21

**Comment by nodiscc** [comment] 2017-01-19 12:52
* auto close: #131
 * scheduling: #63
 * save downloads list: #44
