### ISSUE TITLE
Error downloading video from vod-platform.net

### ISSUE THREAD

**Issue by dreamboxgate** [MrS0m30n3/youtube-dl-gui#238] opened 2017-11-04 10:46 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dl-gui** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/docs/faqs.md) file

- [x] **I think** my problem is **NOT** with **youtube-dl**
- [x] I've **verified** and **i assure** that I'm running youtube-dl-gui **0.4**
- [x] **I assure** that i am using the latest version of **youtube-dl**
- [x] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker
- [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **youtube-dl-gui**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
[11/03/17 13:25:12] [debug] System config: []
[11/03/17 13:25:12] [debug] User config: []
[11/03/17 13:25:12] [debug] Custom config: []
[11/03/17 13:25:12] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\Users\ThE MaStEr\Desktop\Downloads\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.vod-platform.net/embed/3r6jVBuRrAWx2x5BJGyiHA?responsive=1&autoplay=0&RelVideos=0', 'https://www.vod-platform.net/embed/3r6jVBuRrAWx2x5BJGyiHA?responsive=1&autoplay=0&RelVideos=0']
[11/03/17 13:25:12] [debug] Encodings: locale cp1256, fs mbcs, out cp1256, pref cp1256
[11/03/17 13:25:12] [debug] youtube-dl version 2017.10.29
[11/03/17 13:25:12] [debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[11/03/17 13:25:12] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[11/03/17 13:25:12] [debug] Proxy map: {}
[11/03/17 13:25:12] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/03/17 13:25:12] WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[11/03/17 13:25:12] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/03/17 13:25:12] Traceback (most recent call last):
[11/03/17 13:25:12] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
[11/03/17 13:25:12] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
[11/03/17 13:25:12] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\vodplatform.py", line 30, in _real_extract
[11/03/17 13:25:12] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 1072, in _sort_formats
[11/03/17 13:25:12] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/03/17 13:25:12]
[11/03/17 13:25:12] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/03/17 13:25:12] WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[11/03/17 13:25:12] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/03/17 13:25:12] Traceback (most recent call last):
[11/03/17 13:25:12] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
[11/03/17 13:25:12] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
[11/03/17 13:25:12] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\vodplatform.py", line 30, in _real_extract
[11/03/17 13:25:12] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 1072, in _sort_formats
[11/03/17 13:25:12] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/03/17 13:25:12]
```

#### What operating system do you use ?

Windows 7

#### List of actions to perform to reproduce the problem:

  1. .. Attempt to download this https://www.vod-platform.net/embed/3r6jVBuRrAWx2x5BJGyiHA?responsive=1&autoplay=0
  2. ..
  3. ..
  
#### What is the expected behaviour ?
It will download the video at its highest/native resolution, 720p

#### What happens instead ?

Error Download
---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?

---

**Comment by nodiscc** [comment] 2017-11-05 12:28
@dreamboxgate thank you for correctly filing the issue :)

> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

It seems to be an issue with the vod-platform.net video extractor in [youtube-dl](https://github.com/rg3/youtube-dl), so it cannot be fixed in youtube-dlg. The correct way to get this fixed is to report the issue to youtube-dl maintainers following their guidelines.

I see you tried to report it to https://github.com/rg3/youtube-dl/issues/14645, but it was closed because you deleted the default issue text (https://github.com/rg3/youtube-dl/issues/new). To get your issue addressed you must

1. Download the latest youtube-dl from https://rg3.github.io/youtube-dl/download.html
2. Go to https://github.com/rg3/youtube-dl/issues/new
3. Run `youtube-dl --version` and make sure you are using the latest version
4. Answer to the `New issue` questions/checkboxes `[x]` like this
5. Run `youtube-dl --verbose 'https://www.vod-platform.net/embed/3r6jVBuRrAWx2x5BJGyiHA?responsive=1&autoplay=0&RelVideos=0'`
6. Paste the program output to the `New issue` template (where `[debug] System config: []` is)

I hope that helps. Just report the issue precisely as they ask (just like you did here).

(This reply can serve as a template for future youtube-dl related issues. I'll add an issue label for that)

Closing, then.

**Closed by nodiscc** 2017-11-05 12:28 UTC

**Comment by dreamboxgate** [comment] 2017-11-06 12:08
Thanks alot
https://github.com/rg3/youtube-dl/issues/14686

**Comment by dreamboxgate** [comment] 2017-11-06 19:02
they close my issue again ?????

**Comment by nodiscc** [comment] 2017-11-06 23:01
I can not help you much more, the maintainer added the `duplicate` tag which means your bug report could be a duplicate of another one. I have searched for `vod-platform` in the issue tracker and could not find anything. You could kindly ask which bug this was a duplicate of. Good luck
