### ISSUE TITLE
provide option to change how many videos at a time

### ISSUE THREAD

**Issue by answerquest** [MrS0m30n3/youtube-dl-gui#157] opened 2017-03-07 05:31 UTC
### Before going further

  - [x ] **I assure** that my problem is **NOT** with **youtube-dl**
  - [x ] I've **verified** and **I assure** that I'm running youtube-dl-gui **0.3.8**
  - [x ] **I assure** that i am using the latest version of **youtube-dl**
  - [x ] [Searched](https://github.com/MrS0m30n3/youtube-dl-gui/issues) bugtracker

---

### What is the purpose of your *issue*?
- [ ] Bug during the download process (encountered problems after hitting the *Download* button)
- [ ] Bug other (encountered other problems with *youtube-dl-gui*)
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information. Please make sure the description is worded well enough to be understood.

Please provide an option to let user set how many videos to download at one time. This option could be included in the "Connections" tab. At my end I can see the default is 3 at a time; if there are more URLs then the program waits for the earlier ones to finish or error out. I am seeing that something is causing downloads to slow down and die out midway and I want to try running my queue one video at a time instead. (when I do with just one URL at a time, it usually works perfectly.) 

I have a relatively slower internet connection than the developed world (below 1mbps) and one-at-a-time downloads work much better here even in other download managers. I'm running this on a Lubuntu 16.04 LTS OS. Alternatively, kindly point me to where I can make an edit in the program to change the max number of simultaneous downloads at my own end.

**Comment by nodiscc** [comment] 2017-03-07 08:25
Duplicate of https://github.com/MrS0m30n3/youtube-dl-gui/issues/20#issuecomment-71318295

**Closed by nodiscc** 2017-03-07 08:25 UTC

**Comment by answerquest** [comment] 2017-03-08 07:51
thank you! setting "workers_number": 1 in the settings.json file made it so much better! I guess I forgot to check the closed issues, didn't realize I was seeing only the open ones, sorry!
